import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className= {`${montserrat.className} h-screen w-screen antialiased bg-gradient-to-b from-blue-50 to-[#e3efff] flex flex-col items-center pt-12 md:pt-12`}
      >
        {children}
      </body>
    </html>
  );
}
